### PR TITLE
Added default support for FormItem::select

### PR DESCRIPTION
**Pull request by SubniC**
I added default value support for selects, i was not able to do it for multiSelect yet.

best regards.

### CODE REVIEW

**Comment by sleeping-owl** [comment]
Thanks. Your pull request contains commits from branch for laravel 5, so I can't merge it. I added your latest commit by myself.

**Comment by SubniC** [comment]
ok, thanks, is first time i try to collaborate and it is still a bit messy for me.

I'll try again with the next thing :)

**Comment by SubniC** [comment]
For select it is working fine, but i cant get it working for multilecet fields.

best regards.

**Comment by sleeping-owl** [comment]
Fixed this

**Pull request closed without merging**
